### PR TITLE
Fix the hasbang so it works on FreeBSD

### PR DESCRIPTION
**Pull request by 0xR**
On my FreeBSD system bash is at /usr/local/bin/bash
By using the hasbang `$!/usr/bin/env bash` it works on
any system

### CODE REVIEW

**Comment by g00nix** [comment]
This gets proposed every week but nobody ever fulfills the requirements for this to actually get pushed to master:

- confirm that the fix does not break functionality for any of the distributions mentioned in the ReadMe
- confirm that the fix actually makes the scripts work on FreeBSD (meaning no other fixes except the shebang are needed)

Most times the answer is along these lines: https://github.com/pia-foss/manual-connections/issues/105#issuecomment-808970989

It would help a lot if you would actually test the stuff mentioned above so that we can proceed to merging this to master.

**Comment by john-parton** [comment]
No one's going to install 8 operating system to check a __painfully__ trivial change. It's just unreasonable to ask a first-time contributor to do so.

**Comment by g00nix** [comment]
> No one's going to install 8 operating system to check a painfully trivial change. It's just unreasonable to ask a first-time contributor to do so.

It's best practice to test modifications before pushing them to git, no matter how trivial the modifications are.

We have tested the modification internally and we have still found bugs that cause the script not to be usable on FreeBSD, so the modification you proposed do not fix the issue.

There are also [other PRs](https://github.com/pia-foss/manual-connections/pull/106) that have proposed the same change before you submitted your PR. If you check the PR page on any github project, you will see there is a search field at the top.

**Comment by john-parton** [comment]
> There are also [other PRs](https://github.com/pia-foss/manual-connections/pull/106) that have proposed the same change before you submitted your PR. If you check the PR page on any github project, you will see there is a search field at the top.

That other PR *is* my PR. Look at the author. This PR is the duplicate.

I never claimed that this would fix FreeBSD. I simple authored the smallest change that I **thought** could be easily merged.

**Comment by g00nix** [comment]
@john-parton you just answered on the PR from @0xR 

But thank you for your message. 😺

**Pull request closed without merging**
