### PR TITLE
Move transient/temporary file out of /opt

### LINKED ISSUE #23: Use /tmp and /run instead of /opt/piavpn-manual
`/opt` should be considered read-only by the scripts.

Temporary files should be stored in `/tmp` or better a directory in `/tmp` created with `mktemp`. For example

    tmpdir=`mktemp -d -p /tmp -t piavpn-manual-XXXXX.d`
    echo $tmpdir
    /tmp/piavpn-manual-k5cVRf.d

The random portion of the directory name is crucial for the security and avoid race conditions.

It is not yet in the **FHS**, but it is already largely  used that `/run` is used for transient like pid_file of process or services.

For example in `run/piavpn-manual` could be stored resolv_conf_backup, pia_pid, route_info, etc ... if some are not stored in `/tmp`

This is linux-centered and I don't know of BSDs ...

### PR DESCRIPTION
**Pull request by solsticedhiver**
We use `/var/opt/piavpn-manual` to store most of the files except the **pid file** which is stored in `/var/run` as most of daemon script always do.
We use `/var/run` instead of `/run` because of FreeBSD.

`/var/opt` and:
- not `/run` because it is mounted with noexec on some distro
- not `/tmp` because an admin could mount it too with noexec

* we use a umask of 0077 to disable read of any other user than root
* along the way, fix tiny bugs:
  - where pia-manual directory was used instead of piavpn-manual
  - use -N for `curl |head` to avoid a 'Failed writing body' error message
  - move a line to avoid an unnecessary error when openvpn connection fails
    
close #23

### CODE REVIEW

**Comment by g00nix** [comment]
On which distributions did you test this? Is it safe to merge this to master?

**Comment by solsticedhiver** [comment]
I tested this on archlinux-arm.
The wireguard stuff works fine, but it is unaffected by the change I think.

For openvpn, I don't know.

**Comment by solsticedhiver** [comment]
So I found the bug in the changes I introduce.
On ubuntu, /run is mounted with noexec, so the openvpnup/down script can't be run.

So I move them to /var/lib instead of /var/run. It's becoming a little too much with files in /var/run and /var/lib. But o we have the choice ?

I still get that error:
     cat : route_info not found

**Comment by g00nix** [comment]
@solsticedhiver the distributions that should be tested are: Arch or Manjaro, Debian or Ubuntu, Fedora.

Did you try using `/tmp/piavpn-manual`?

**Comment by solsticedhiver** [comment]
No, I did not try `/tmp/piavpn-manual`.

Do you mean change `/var/run` and `/var/lib` to `/tmp` ? Yes. that could do it.
Do you prefer `/tmp/piavpn-manual` I am not a fan of that. But that's a matter of preference I guess.

But then I would have to advice not to use `chmod 600` on credentials but use a `umask 0077` instead.
this would avoid any user reading the file in `/tmp/piavpn-manual`

**Comment by g00nix** [comment]
> Do you prefer `/tmp/piavpn-manual` I am not a fan of that. But that's a matter of preference I guess.

If it works on all distributions, we can use that.

> But then I would have to advice not to use `chmod 600` on credentials but use a `umask 0077` instead.

This has to be tested the same way as everything else to make sure we don't break any of the existing functionality.

**Comment by solsticedhiver** [comment]
I kept `/var/run` for the **pid** file as it is usually kept there.
The rest is in `/tmp/piavpn-manual` now.

I woudl like to test it more, but I have still the other bug. Should I open a new bug for that one ?

**Comment by iPherian** [comment]
@solsticedhiver try looking at the ovpn log, it's usually pretty descriptive.

**Comment by solsticedhiver** [comment]
@iPherian 
well there is not much to look there:

```
Mon Nov 16 20:29:08 2020 OpenVPN 2.4.9 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Aug 18 2020
Mon Nov 16 20:29:08 2020 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Mon Nov 16 20:29:08 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Nov 16 20:29:08 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]84.17.60.215:501
Mon Nov 16 20:29:08 2020 UDP link local: (not bound)
Mon Nov 16 20:29:08 2020 UDP link remote: [AF_INET]84.17.60.215:501
Mon Nov 16 20:29:19 2020 event_wait : Interrupted system call (code=4)
Mon Nov 16 20:29:19 2020 SIGTERM[hard,] received, process exiting
```
I don't know what is going on.
Why is there is no tun interface ? Is it the server not responding ?

**Comment by g00nix** [comment]
@solsticedhiver 501 is a TCP port. How did you land on that port via UDP?

**Comment by solsticedhiver** [comment]
@g00nix you tell me ?

Something is very **wrong**:
`./connect_to_openvpn_with_token.sh` is expecting a CONNECTION_SETTINGS back from the server in the form of: `protocol encryption`
but what I got is: `openvpn` !
the script is expecting someting like "tcp/udp standard/strong". so the script is bugging because of this

the script is reading CONNECTION_SETTINGS; it got protocol="" and encryption=""
and this ends with pia.opvn having the last line like

    remote 143.244.57.183 501

I am given back the paris server (paris402, paris 40x, ...)

Has anyone tested that script ? Is it only that server that is wrong ?

**Comment by solsticedhiver** [comment]
Seeing that `/tmp` could be mounted with noexec too by some admin, I changed the directory again, this time  to `/var/opt`, which is supposed to hold variable data for /opt package (where this is supposed to be installed) and where scripts vould be executables.

**Comment by g00nix** [comment]
> Seeing that `/tmp` could be mounted with noexec too by some admin

I think it's important to know if it gets mouted by default as noexec or not, not by the admin.

I think we can keep the scripts in `/opt/piavpn-manual` and the sensitive data in `/tmp/` or `/var/run/`

**Comment by solsticedhiver** [comment]
I don't think I can check every distro to see if `/tmp` is mounted wiht **noexec**. And most likely, very few must do that.

But I don't like to use `/tmp` for those file because this is a place where everyone has write-access. And this allow a symlink attack to take place. See https://en.wikipedia.org/wiki/Symlink_race

But we could use a temp dir with random string with `mktemp`. It just complicate things a little. But if you really want to use `/tmp`, I could do it.
May be, I am too security aware/sensible ?

**Comment by g00nix** [comment]
> May be, I am too security aware/sensible ?

Yes, but you are not the first one to be against the use of `/opt/`. There just wasn't anybody to invest the required time to find a better solution that actually works for all distros.

**Comment by g00nix** [comment]
As the repo changed a lot with the release of [v2.0.0](https://github.com/pia-foss/manual-connections/tree/v2.0.0), I think we should close this PR and open a new one. The issue still stays opened till we clarify this situation.

**Comment by StudioEtrange** [comment]
Any idea on this ? moving files to a configurable folder which may have as default value /tmp/piavpn (or anything else in /tmp)
I think it will be highly valuable change for a lot of thing
(And in the same time remove the needs of beeing root on some of the scripts (not all but some) who wants to write into /opt)

**Comment by g00nix** [comment]
I think nobody spent the time to move data to other folders and test on all distros. I think everybody agrees this should be done at a certain point, but nobody dedicated the time to ensure compatibility. @StudioEtrange you are very active and also have some advanced technical skills, but the if you tackle this issue please make sure all comments are well written and that the code is easy to to understand also for people new to scripting. The repo has to stay accessible.

I am super happy with v2.0.0. It covers a lot of things that we wanted to release since September. I think we can build on top of this.

**Pull request closed without merging**
