### PR TITLE
Splits get_region and get_token to separate scripts and adds server selection ability to run_setup

### PR DESCRIPTION
**Pull request by faireOwl**
Get region and get token now operate separately, if calling one directly with the intent of connecting like the old setup, get_region is the default script to call.

### CODE REVIEW

**Comment by g00nix** [comment]
I think this code is clean. It could use some small improvements, but the general idea and direction is very good.

@dom11990 and @iPherian: This was a change that you requested and recommended. What do you think about [this fork](https://github.com/pia-foss/manual-connections)?

**Comment by iPherian** [comment]
@g00nix Looks good, apart from minor improvements as you say, and one suggestion: Make get_token accept the meta ip and hostname as env vars so it doesn't have to do a full region scan each time. Example in his fork: PR faireOwl/manual-connections#1

@faireOwl

**Comment by g00nix** [comment]
We need to set up a permanent endpoint that allows you to generate tokens, so that you are not forced to go through the meta to get your token. This will allow you to properly separate get_region and get_token, since you won't need the region to get the token.

This mostly means this project will get postponed by another week, till we manage to host the new endpoint. I will try to get it done faster, but no promises. :smile_cat:

**Comment by g00nix** [comment]
Merged to https://github.com/pia-foss/manual-connections/tree/v2.0.0
Closing this PR.

**Pull request closed without merging**
