### PR TITLE
Add note about meta service api

### PR DESCRIPTION
**Pull request by gameman733**
Added a note about using the internal meta service api for those customizing or creating their own scripts. Issue #10 mentioned adding something to the read me, but I don't see where that was done.

### CODE REVIEW

**Comment by iPherian** [comment]
```diff
+# NOTE for those customizing this script
+# If you are already connected to PIA, this will fail.
+# replace $bestServer_meta_IP with 10.0.0.1 to contact the 
+# meta interface.
...
curl $bestServer_meta_IP # the public ip
```
[commit](https://github.com/pia-foss/manual-connections/pull/39/files#diff-44093944cfc327d70ffab5c108bbf3f6630db921528ccd98331b6b1b83d0b551R149-R153)

Thanks for the PR, although I think this note is not quite accurate. That line is accessing the meta server at it's public ip, which (if one knows it) iirc works just fine if you are inside the vpn. Perhaps what should be said instead (somewhere) is that the *best* way to access the meta server while already connected is 10.0.0.1. ( because the scripts don't remember the public meta ip ).

But it would indeed be helpful to have this documented: It makes things much simpler!

In detail, the issue you mentioned was someone trying to get a token (which are given by meta servers) at the *gateway* server, who don't give tokens no matter what ip they're accessed at.

**Comment by gameman733** [comment]
Thank you for the feedback! I'll be honest, I don't have a great understanding on PIA's network and new authentication mechanisms, so I'm open to any correction on my misunderstandings. I was approaching this last night as a "my random port forward script stopped working, how do I make it work again" which was using the old API where you gave your vpn IP, a token, and some other info (username and pass possibly).  

> That line is accessing the meta server at it's public ip, which (if one knows it) iirc works just fine if you are inside the vpn

Is this supposed to work? The impression I'm under from my troubleshooting/research last night was that it doesn't appear to be. See below. It failed for me (already connected to PIA, ro.privacy.network over openvpn, port 1198) until I changed the public ip for 10.0.0.1. 

# curl -v -u USER:PASS --cacert ca.rsa.4096.crt --connect-to romania407::143.244.54.119: https://romania407/authv3/generateToken
* Expire in 0 ms for 6 (transfer 0x559ba54dfbb0)
* Connecting to hostname: 143.244.54.119
*   Trying 143.244.54.119...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559ba54dfbb0)
* connect to 143.244.54.119 port 443 failed: No route to host
* Failed to connect to 143.244.54.119 port 443: No route to host
* Closing connection 0
curl: (7) Failed to connect to 143.244.54.119 port 443: No route to host

This is what led me to #10 (which I didn't notice was connecting to a gateway, thanks for the clarification). Specifically, the comment about using the 10.0.0.1 meta server.

**Comment by iPherian** [comment]
@gameman733 Well, i'll be damned, you're right. It seems connecting to the current meta server via it's public ip fails. For me it was a timeout, but when I changed to 10.0.0.1 I got the token immediately.

I think I didn't notice because these scripts sometimes connect to a different meta server in the same region. E.g. I like you connected to romania407, and then I ran the script again and it tried to connect to romania408 and it did successfully get a token there. (and so I assumed everything was fine). But that's technically a different server, which is the distinction I guess. Attempting to get a token from romania407 (the same server) fails.

Oops. 😉

**Comment by g00nix** [comment]
This is clearly an area that needs to transmitted in a better way to people modifying the scripts, however we might have to change a lot of stuff to implement 2 other modifications that are highly required:

1. allowing people to connect to a specific region
2. allowing people to enable port forwarding when already connected to OpenVPN

Considering that and considering the repo might change a lot to accommodate the two requirements above, I think we should postpone the documentation improvements till we get the rest of the stuff done.

**Comment by g00nix** [comment]
This script got split as part of the [v2.0.0 release](https://github.com/pia-foss/manual-connections/tree/v2.0.0). Please inspect the new release to see if your find the new comments acceptable. If you still feel like changes should be made, please submit a new PR or open a ticket.

**Pull request closed without merging**
