### PR TITLE
Add support for OpenWRT OpenVPN port forwarding

### PR DESCRIPTION
**Pull request by etomm**
This add a file owrt_pf.sh that can be used as up script and can be scheduled in cron in an OpenWRT installation to expose the forwarded port into http://<routeripandport>/pia_pf.json

### CODE REVIEW

**Comment by g00nix** [comment]
I think we should create a special folder with documentation and scripts for openwrt, so that we do not break compatibility for the rest of the distributions that mostly work with the same automation.

My idea is the following: we do a `extra` folder and an `openwrt` subfolder, and we make a nice readme and also add the PF script and maybe other scripts that openwrt would benefit from.

What do you think?

**Comment by etomm** [comment]
For me it is fine. Will you prepare a branch with the base structure on
which I will insert the various scripts?

Keep in mind that the modifications to the port forwarding script are done
in a way that should not break compatibility with the rest of the world and
in fact in some cases could benefit from it, like the ability to create a
cron job and the fact that a script gets called when the port forward is
successful.

I saw there is another PR that was requesting for the ability to save the I
think token or signature and payload. With the modification in this PR it
is easy to create a callback script to do it, that in fact is what is being
done for openwrt to avoid to have the script running forever.

**Comment by g00nix** [comment]
>  Will you prepare a branch with the base structure on which I will insert the various scripts?

Yes. Thank you for getting involved.

> Keep in mind that the modifications to the port forwarding script are done
in a way that should not break compatibility with the rest of the world and
in fact in some cases could benefit from it, like the ability to create a
cron job and the fact that a script gets called when the port forward is
successful.

Thank you for the confirmation. I will do my best to review the code in a timely manner.

> I saw there is another PR that was requesting for the ability to save the I
think token or signature and payload.

I am thinking about improving this system.

> With the modification in this PR it
is easy to create a callback script to do it, that in fact is what is being
done for openwrt to avoid to have the script running forever.

I saw, that's what I am suggesting a separate folder. OpenWRT is totally different from the other systems. That's why I don't think OpenWRT will run into conflicts by running the code for other distros, mostly because that code will never run on their system. I think it's just easier to separate them completely.


I'll create the branch

**Comment by g00nix** [comment]
https://github.com/pia-foss/manual-connections/tree/openwrt_testing/extra/openwrt

**Pull request closed without merging**
